### ISSUE TITLE
New_tab missing

### ISSUE THREAD

**Issue by debeetle** [Pandademic/rose#1]
I love gtk4 and webkit2gtk-5.0! But I cannot find code about creating a new tab. Did I miss something? Look forward to your replying.

**Comment by Pandademic** [comment]
hi there @debeetle!

This is actually a fork of [mini-rose's web browser](https://github.com/mini-rose/rose), and has not been updated from upstream(nor been pushed to be me) in quite sometime.I haven't actually looked at this in quite a while.However at upstream you could be able to find the code [here, in the function new_tab](https://github.com/mini-rose/rose/blob/master/rose.c#L176-L189). But beware, as upstream has **a lot** since this fork was made, and doesn't fully resemble this fork anymore, as this one is much much more "retro" and less feature complete(and probably simpler),. I figure you would like to look at in upstream, however if this humble fork continues to hold your intrigue after looking upstream, please reply with an @-mention telling me so, and I will look into it for you.Lastly, I don't believe that the commit this is forked from(it had some cherry-picking on my part) has tabs, but if you would like I could add them from upstream, or add them my self.If you see this as a serious project, and plan on using it, then I'm very sorry, as I didn't except anyone to see this humble fork over the  upstream one, and so forgot to actually push anything to it.
